### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RisingIPhoenix** [AMPZNetwork/All-The-Forge-9#1]
**Describe the bug**
The usual menu design changed since the 1.2. Update and there seems to be no internal Shader support anymore. Not sure if it's a bug tho or inteded.

**To Reproduce**
Load the Game

**Expected behavior**
Expected an integraded shader loader like in the last version

**Crash Log**

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows
 - All The Forge 9 Version 1.2
 - Platform AT Launcher
 -Extra Mods None

**Comment by LabsZero** [comment]
Shaders support was removed in v1.1+ along with Rubidium for better compatibly.

You're more than welcome to add it manually
