### ISSUE TITLE
ATLF9 with Optifine crashes when loading immersive engineering items in JEI menu??

### ISSUE THREAD

**Issue by 99powerbreaker** [AMPZNetwork/All-The-Forge-9#2]
**Describe the bug**
The game seems to crash whenever loading objects such as the drill or a florescent tube from the JEI menu. It seems to only be items from immsersive engineering.

**To Reproduce**
1. Open a world.
2. Click on the JEI search bar and search FL (or anything from immersive engineering)
3. crash.

**Expected behavior**
For the Game not to crash and be able to load.

**Crash Log**
[crash-2023-01-02_21.25.29-client.txt](https://github.com/AMPZNetwork/All-The-Forge-9/files/10334074/crash-2023-01-02_21.25.29-client.txt)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - All The Forge 9 Version v1.4
 - Platform: ATLauncher
 - Optifine Pre Release 4

**Comment by LabsZero** [comment]
Thank you for you big report I she’ll look into a fix as soon as possible.

**Comment by 99powerbreaker** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5518 It seems that immsersive engineering does not support optifine.
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/CONTRIBUTING.md here as well 
![image](https://user-images.githubusercontent.com/99379078/210400364-b2f75994-591c-40b7-99cf-93a125b43aae.png)
You can still try to fix it if you want but through doing a little more research here is what I found. It seems a decent amount of mods don't officially support optifine but since I do not program or code I do not know if there are workarounds. I thought I would share my findings anyway.
