### ISSUE TITLE
[BUG] Typing "ladder" into JEI search bar causes a crash with Optifine installed

### ISSUE THREAD

**Issue by HowardRoark2016** [AMPZNetwork/All-The-Forge-9#4]
**Describe the bug**
Playing All The Forge 9 v1.9.0. When I try to type the word "ladder" into JEI with Optifine installed, the game crashes instantly after I type just "la". Searching for "apple" does not induce a crash. Removing Optifine (but keeping the three other mods I installed) resolves the crash issue.

**To Reproduce**
1. Install Optifine
2. Tap on "E" key to enter JEI
3. Begin to type "ladder" into the search bar
4. See crash after typing just "la"

**Expected behavior**
Game immediately crashes to desktop upon typing "la" into JEI search bar

**Crash Log**
https://pastebin.com/jPViUf3F

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - All The Forge 9 Version 1.9.0
 - Extra mods added by you -- [veinmining-forge-1.1.1+1.19.2](https://www.curseforge.com/minecraft/mc-mods/vein-mining), OptiFine_1.19.2_HD_U_I1, [Enhanced_Celestials-forge-1.19.2-2.1.0.5](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials), [CorgiLib-forge-1.19.2-1.0.0.34
](https://legacy.curseforge.com/minecraft/mc-mods/corgilib)

**Comment by LabsZero** [comment]
Issue fixed in the latest version, also make sure to download the new Optifine version as well.
