### ISSUE TITLE
[BUG] my backpack got wiped on the new update

### ISSUE THREAD

**Issue by AP2B1** [AMPZNetwork/All-The-Forge-9#7]
**Describe the bug**
my backpack got wiped when i updated the mod

**To Reproduce**
1. Have a backpack full of stuff
2. Log of the game
3. Update the mod 
4. Log back on
5. Sadness

**Screenshots**
![20230828_180428](https://github.com/AMPZNetwork/All-The-Forge-9/assets/143453502/27e5c060-f1c9-4316-9fd8-271f996cd0e1)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - All The Forge 9 Version 12
 - Platform: sophisticated backpacks

**Comment by LabsZero** [comment]
How strange this update did not update sophisticated backpacks 🤔. Before I check to see if this is a bigger problem was you on our official sever at all or your own single player world?

**Comment by AP2B1** [comment]
I was on my single player world. I might add that the backpack was bugging a little

**Comment by LabsZero** [comment]
Probably that what caused your backpack to wipe as I’ve attempted to copy this bug without no success.
