### ISSUE TITLE
[BUG] Macaws Bridges missing pliers

### ISSUE THREAD

**Issue by Laurentyb** [AMPZNetwork/All-The-Forge-9#8]
**Describe the bug**
The pliers required for modifying the enterances to Macaws bridges appears to be missing and cannot be found in NEI.
Without these you cannot use Macaws bridges in anything other than 1 block wide configuration.

**To Reproduce**
1. Search NEI for Pliers or @Macaws Bridges to see all mod blocks
2. No pliers available

**Expected behavior**
Ability to see pliers in NEI and craft them.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - All The Forge 9 Version 11
 - Platform AT
 - Extra mods added by you  N/A

**Comment by LabsZero** [comment]
Your using an older version of the pack, try updating to v12 to see if your issue is still there.

**Comment by Laurentyb** [comment]
Pliers appear to be avaialble in version 12. 
How do you recommend updating servers? When I copied the world files over from v11 to fresh copy of ATF9 server v12 I get block ID scrambling.

**Comment by LabsZero** [comment]
You need both mods and config folder from the new server files make sure to replace you current server files with them

**Comment by LabsZero** [comment]
If you need any assistance please reach out to us on Discord https://discord.gg/enrpMDd and we will be happy to assist you further

**Comment by Laurentyb** [comment]
Thanks, that worked great. I can confirm that pliers are working in v12.
